Class cls.CDUI.DataGen.MIMIC.LABEVENTSfull Extends %Persistent
{
Property LabEventId As %Integer;

Property SubjectId As %Integer;

Property HadmId As %Integer;

Property SpecimenId As %Integer;

Property ItemId As %Integer;

Property OrderProviderId As %Integer;

Property Charttime As %String;

Property Storetime As %String;

Property Value As %String;

Property Valuenum As %Decimal;

Property Valueuom As %String;
}